# Generated by Django 4.1.3 on 2022-12-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('pk',), 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
