# Generated by Django 4.1.3 on 2022-12-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
