# Generated by Django 4.1.3 on 2022-12-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Involve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamge', models.ImageField(blank=True, upload_to='covers/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
