# Generated by Django 4.1.3 on 2022-12-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getinvolved', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='involve',
            old_name='iamge',
            new_name='image',
        ),
    ]
