# Generated by Django 4.1.3 on 2022-12-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getinvolved', '0002_rename_iamge_involve_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='involve',
            options={'ordering': ('title',), 'verbose_name': 'involved', 'verbose_name_plural': 'involved'},
        ),
    ]
